config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :show, :new, :index, :edit, :update]
  resources :places, only: [:new, :create, :show, :index, :edit, :destroy]
  resources :comments, only: [:new, :create]
  get '/', to: 'static#welcome'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/home/:id', to: 'users#home'
  post '/home/:id', to: 'places#create'

  post '/places/:id', to: 'places#update'
  # get '/users/signup', to: 'users#new'
  # post '/places/:id', to: 'comments#new'
  get '/search', to: 'search#search'
  get '/places/add/:id', to: 'places#add'
  post '/places/add/:id', to: 'places#added'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_places
  has_many :places, through: :user_places
  has_many :comments



  accepts_nested_attributes_for :places
  has_secure_password
  # validates :email, uniqueness: true
  validates_uniqueness_of :email, :case_sensitive => false
  validates :email, :password, :first_name, :last_name, presence: true
  validates :email, 'valid_email_2/email': { mx: true, disposable: true, disallow_subaddressing: true}

  def full_name
    "#{first_name} #{last_name}"
  end

  def visited_places
    self.user_places.select do |user_place|
      user_place[:future] == false
    end.map {|user_place| user_place.place}
  end

  def will_go_to_someday
    self.user_places.select do |user_place|
      user_place[:future] == true
    end.map {|user_place| user_place.place}
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :get_user, only: [:home, :show]
  before_action :require_login
  before_action :authorize_page, only: [:home]
  skip_before_action :require_login, only: [:new, :create]

  def index
    @users = User.all
  end

  def new
    @user = User.new
    @user.places.build
  end

  def create
    @user = User.create(user_params)
    return redirect_to controller: 'users', action: 'new' unless @user.save
    session[:user_id] = @user.id
    redirect_to "/home/#{@user.id}"
  end

  def show

  end

  def home

  end

  def edit
    @user = session_user
  end

  def update
    @user = session_user
    user_params[:bio] = nil if user_params[:bio] == ""
    @user.update_column(:bio, user_params[:bio])
    redirect_to '/'
  end


  private
  #
  # def authorize_page
  #   return head(:forbidden) unless session[:user_id] == @user.id
  # end
  #
  # def require_login
  #   return head(:forbidden) unless session.include? :user_id
  # end

  # def get_user
  #   @user = User.find(params[:id])
  # end


  def user_params
    # params.each { |key, value| value.strip!}
    params.require(:user).permit(:first_name, :last_name, :email, :password, :bio, :password_confirmation, :places_attributes => [:name, :country])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.erb
<div class="add_comment form-group">
  <h1>Biography</h1>
  <h6>Where did you grow up? Tell us your story</h6>

  <%= form_for @user do |f| %>
    <%= f.text_area :bio, size: "60x12", :class => "form-control" %><br>
    <%= f.submit "Submit", :class => "btn btn-primary" %>
  <% end %>
</div>

app/views/users/home.erb
<h1>Welcome <%= @user.full_name %></h1>
<%#= button_to "Log out", logout_path, :method => :delete %>
<h2>Tell us about yourself</h2>

<%= link_to "Biography", edit_user_path, :class => "btn btn-primary add_btn" %><br>

<%= @user.bio %>

<p><h2>Add Places You Have Lived, Visited And Want To Go!</h2></p>

<%= link_to "Add Places", new_place_path, :class => "btn btn-primary add_btn" %>

<div class="all_places">
<div class="been_to">
  <h2>Places You've Visited And Lived!</h2>
  <% @user.visited_places.each do |place| %>
  <ul>
    <li>
      <%= link_to "#{place.city}", place_path(place) %>
      <%= link_to "- Edit", edit_place_path(:place_id => place) %>
    </li>
  </ul>
  <% end %>
</div>

<div class="will_go">
  <h2>Places You Will Go To Someday</h2>
  <% @user.will_go_to_someday.each do |place| %>
  <ul>
    <li>
      <%= link_to "#{place.city}", place_path(place) %>
      <%= link_to "- Edit", edit_place_path(:place_id => place) %>
    </li>
  </ul>
  <% end %>
</div>
</div>

app/views/users/index.erb
<h1>All Users</h1>

<% @users.each do |user| %>
  <p>
    <%= link_to user.full_name, user_path(user) %>
  </p>

  <% end %>

app/views/users/new.erb
    <h1>Sign Up for PlaceMe</h1><br>
    <div class="signup form-group">
    <%= form_for @user do |f| %>

      <%= f.label :first_name %><br>
      <%= f.text_field :first_name,:class => "form-control" %><br>
      <%= f.label :last_name %><br>
      <%= f.text_field :last_name, :class => "form-control" %><br>
      <%= f.label :email %><br>
      <%= f.text_field :email,:class => "form-control" %><br>
      <%= f.label :password %><br>
      <%= f.password_field :password,:class => "form-control" %><br>
      <%= f.label :confirm_password %><br>
      <%= f.password_field :password,:class => "form-control" %><br>
      <%= f.submit "Sign Up", :class => "btn btn-primary" %>
    <% end %>
  </div>

app/views/users/show.erb
<h1><%= @user.full_name %></h1>

<h2>About</h2>

<%= @user.bio %>

<div class="all_places">
  <div class="been_to">
    <h2>Places I've Visited And Lived!</h2>
    <% @user.visited_places.each do |place| %>
    <ul>
      <li>
        <%= link_to "#{place.city}", place_path(place) %>

      </li>
    </ul>
    <% end %>

  </div>

  <div class="will_go">
    <h2>Places I will Go To Someday</h2>
    <% @user.will_go_to_someday.each do |place| %>
    <ul>
      <li>
        <%= link_to "#{place.city}", place_path(place) %>
      </li>
    </ul>
    <% end %>
  </div>
</div>